version: '3'

services:
  first_prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - first_prod
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5433
    env_file:
      - ./.env.db

volumes:
  postgres_data:

