"""empty message

Revision ID: 75a76a61a076
Revises: e7d9108eb801
Create Date: 2024-02-24 17:18:58.671911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a76a61a076'
down_revision: Union[str, None] = 'e7d9108eb801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_owner_name_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['owner_name'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_owner_name_fkey', 'blogs', 'users', ['owner_name'], ['username'])
    # ### end Alembic commands ###
